# Generated by Django 2.2.17 on 2025-06-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_badge_internal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is visible'),
        ),
    ]
