# Generated by Django 2.2.17 on 2023-11-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='show_badge',
        ),
        migrations.RemoveField(
            model_name='image',
            name='internal_link',
        ),
    ]
