# Generated by Django 2.2.17 on 2023-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='view',
            field=models.CharField(choices=[('grid', 'Grid Layout')], default='grid', max_length=50, verbose_name='Gallery View'),
        ),
    ]
