# Generated by Django 2.2.17 on 2023-11-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20231111_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='sorting',
            field=models.CharField(choices=[('numbers', 'By Numbers'), ('random', 'Random')], default='numbers', max_length=50, verbose_name='Sorting'),
        ),
    ]
