# Generated by Django 2.2.17 on 2023-09-23 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='team_teamlist', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('team', models.CharField(choices=[('doctor', 'Doctor'), ('team', 'Team ')], default='doctor', max_length=50, verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='is_visible')),
                ('name', models.CharField(help_text='Full name', max_length=255, verbose_name='Name')),
                ('function', models.CharField(blank=True, max_length=255, verbose_name='Function')),
                ('team', models.CharField(choices=[('doctor', 'Doctor'), ('team', 'Team ')], default='doctor', max_length=50, verbose_name='Team')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Position')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Person',
            },
        ),
    ]
