# Generated by Django 2.2.17 on 2023-10-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='academic_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Academic title'),
        ),
    ]
