# Generated by Django 2.2.17 on 2023-10-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_internal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='template',
            field=models.CharField(choices=[('dynamic', 'Dynamic height'), ('flex', 'Flex height')], default='dynamic', max_length=50, verbose_name='Template'),
        ),
    ]
