# Generated by Django 2.2.17 on 2023-09-30 15:42

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentForm',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='formappointment_appointmentform', serialize=False, to='cms.CMSPlugin')),
                ('receiver_email', models.EmailField(max_length=254, verbose_name='receiver email')),
                ('sent_message', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='this message is shown when the user has sent the form', verbose_name='send mesage')),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Subject')),
                ('email_text', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='this message is shown in the email the user gets', verbose_name='email_text')),
            ],
            options={
                'verbose_name': 'Appointment form',
                'verbose_name_plural': 'Appointment forms',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
