# Generated by Django 2.2.17 on 2023-09-11 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spacer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='spacer_spacer', serialize=False, to='cms.CMSPlugin')),
                ('distance', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=10, verbose_name='Distance')),
            ],
            options={
                'verbose_name': 'Spacer',
                'verbose_name_plural': 'Spacer',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
