# Generated by Django 2.2.17 on 2023-11-11 10:26

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0002_auto_20231110_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobox',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show InfoBox on page. If start date and end date are set, Info Box is only shown between start_date and end_date.', verbose_name='is visible'),
        ),
        migrations.AlterField(
            model_name='infobox',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Text'),
        ),
    ]
