# Generated by Django 2.2.17 on 2023-10-01 14:38

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('mailform', '0002_auto_20231001_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_form_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
    ]
