# Generated by Django 2.2.17 on 2023-09-11 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('is_vertical_centered', models.BooleanField(default=False, verbose_name='vertical centered')),
                ('show_box', models.BooleanField(default=False, verbose_name='show box')),
                ('width_md', models.CharField(choices=[('0', 'auto cols'), ('1', '8%, 1 col'), ('2', '16%, 2 cols'), ('3', '25%, 3 cols'), ('4', '33,3%, 4 col'), ('5', '42%, 5 cols'), ('6', '50%, 6 cols'), ('7', '58%, 7 cols'), ('8', '66%, 8 cols'), ('9', '75%, 9 cols'), ('10', '84%, 10 cols'), ('11', '92%, 11 cols'), ('12', '100%, 12 cols')], default='6', max_length=50, verbose_name='width md')),
                ('offset_md', models.CharField(choices=[('-', 'not set'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='-', max_length=50, verbose_name='offset md')),
                ('width_lg', models.CharField(choices=[('0', 'auto cols'), ('1', '8%, 1 col'), ('2', '16%, 2 cols'), ('3', '25%, 3 cols'), ('4', '33,3%, 4 col'), ('5', '42%, 5 cols'), ('6', '50%, 6 cols'), ('7', '58%, 7 cols'), ('8', '66%, 8 cols'), ('9', '75%, 9 cols'), ('10', '84%, 10 cols'), ('11', '92%, 11 cols'), ('12', '100%, 12 cols')], default='0', max_length=50, verbose_name='width lg')),
                ('offset_lg', models.CharField(choices=[('-', 'not set'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='-', max_length=50, verbose_name='offset lg')),
                ('width_xl', models.CharField(choices=[('0', 'auto cols'), ('1', '8%, 1 col'), ('2', '16%, 2 cols'), ('3', '25%, 3 cols'), ('4', '33,3%, 4 col'), ('5', '42%, 5 cols'), ('6', '50%, 6 cols'), ('7', '58%, 7 cols'), ('8', '66%, 8 cols'), ('9', '75%, 9 cols'), ('10', '84%, 10 cols'), ('11', '92%, 11 cols'), ('12', '100%, 12 cols')], default='0', max_length=50, verbose_name='width xl')),
                ('offset_xl', models.CharField(choices=[('-', 'not set'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='-', max_length=50, verbose_name='offset xl')),
                ('width_xxl', models.CharField(choices=[('0', 'auto cols'), ('1', '8%, 1 col'), ('2', '16%, 2 cols'), ('3', '25%, 3 cols'), ('4', '33,3%, 4 col'), ('5', '42%, 5 cols'), ('6', '50%, 6 cols'), ('7', '58%, 7 cols'), ('8', '66%, 8 cols'), ('9', '75%, 9 cols'), ('10', '84%, 10 cols'), ('11', '92%, 11 cols'), ('12', '100%, 12 cols')], default='0', max_length=50, verbose_name='width xxl')),
                ('offset_xxl', models.CharField(choices=[('-', 'not set'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='-', max_length=50, verbose_name='offset xxl')),
                ('order', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=50, verbose_name='order')),
                ('order_md', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=50, verbose_name='order md')),
                ('order_lg', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=50, verbose_name='order lg')),
                ('order_xl', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=50, verbose_name='order xl')),
                ('order_xxl', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=50, verbose_name='order xxl')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='column_column', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MultiColumns',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='column_multicolumns', serialize=False, to='cms.CMSPlugin')),
                ('background_color', models.CharField(choices=[('white', 'white'), ('cyan', 'cyan')], default='white', max_length=50, verbose_name='background color')),
                ('padding', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=50, verbose_name='padding')),
                ('is_fluid', models.BooleanField(default=False, verbose_name='fluid')),
                ('has_gutters', models.BooleanField(default=True, verbose_name='gutters')),
                ('anchor_id', models.SlugField(blank=True, help_text='unique id to create a anchor to this point', null=True, verbose_name='Anchor Id')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
