# Generated by Django 2.2.17 on 2023-12-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='margin_bottom',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=50, verbose_name='margin bottom'),
        ),
        migrations.AddField(
            model_name='column',
            name='margin_top',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=50, verbose_name='margin top'),
        ),
    ]
