# Generated by Django 2.2.17 on 2023-09-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image_height',
            field=models.CharField(choices=[('min-vh-100', 'Height 100%'), ('min-vh-75', 'Height 50%'), ('min-vh-50', 'Height 50%')], default='min-vh-100', max_length=50, verbose_name='Image height'),
        ),
    ]
