# Generated by Django 2.2.17 on 2023-09-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_image_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image_height',
            field=models.CharField(choices=[('vh-100', 'Height 100%'), ('vh-75', 'Height 50%'), ('vh-50', 'Height 50%')], default='vh-100', max_length=50, verbose_name='Image height'),
        ),
    ]
