# Generated by Django 2.2.17 on 2023-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_auto_20230923_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='template',
            field=models.CharField(choices=[('content-bottom', 'Content bottom'), ('content-top', 'Content top')], default='content-bottom', max_length=50, verbose_name='Template'),
        ),
    ]
